export const VIEW_HOME = 'VIEW_HOME';
export const VIEW_DETAIL = 'VIEW_DETAIL';

export const ACTION_INIT_DATA = 'INIT_DATA';
export const ACTION_SET_VIEW = 'SET_VIEW';
export const ACTION_SAVE_DATA_TO_SALESFORCE = 'ACTION_SAVE_DATA_TO_SALESFORCE';
export const ACTION_SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';